services:
  mysql:
    image: lephuc101/glasses-store-mysql:8.0
    environment:
      MYSQL_DATABASE: glasses_store
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: 'redis:7.4'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: always

  backend:
    image: lephuc101/glasses-store-backend:latest
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/glasses_store?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DOCKER_COMPOSE_ENABLED: "false"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    restart: on-failure

  frontend:
    image: lephuc101/glasses-store-frontend:latest
    build:
      context: ./ecommerce-react
    ports:
      - '80:80'
    depends_on:
      - backend
    restart: always

volumes:
  mysql_data:
  redis_data:
