spring.application.name=glasses-store
# Thiết lập Username
spring.security.user.name=admin

# Thiết lập Password
spring.security.user.password=123456

# (Tùy chọn) Thiết lập Role
spring.security.user.roles=ADMIN